# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Medium Post
        # You may pin to the exact commit or the version.
        # uses: InfraWay/post-medium-action@a44151202cf86ef60efef108bf2a707c4719a168
        uses: InfraWay/post-medium-action@v1.6.0
        with:
          # Medium's App ID
          app_id: offport
          # Medium's App ID
          app_secret: 
          # Medium's Access Token
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          # Markdown post file
          markdown_file: README.md
          # Base blog's URL. Example: https://offport.medium.com
          base_url: https://offport.medium.com # optional, default is 
          # Base blog's post URL. Example: https://myblog/posts
          post_url: https://offport.medium.com/posts # optional, default is 
          # Post's status. Valid values are 'draft', 'public', or 'unlisted'
          post_status: # optional, default is draft
          # Post's license. Valid values are 'all-rights-reserved', 'cc-40-by', 'cc-40-by-sa', 'cc-40-by-nd', 'cc-40-by-nc', 'cc-40-by-nc-nd', 'cc-40-by-nc-sa', 'cc-40-zero', 'public-domain'
          post_license: # optional, default is all-rights-reserved
